### ISSUE TITLE
Support for communication platforms

### ISSUE THREAD

**Issue by harismumtaz18** [sailuh/kaiaulu#133]
Does Kaiaulu provide support for getting communication from other platforms, such as jira, github discussion?

**Comment by carlosparadis** [comment]
Thanks for re-posting here so I can more easily refer. 

Support for JIRA was added a few months past: 
 - https://github.com/sailuh/kaiaulu/commit/2ef0aefdb9e2c46670bb29aa1da24ea94b06251e

Whereas support for GitHub Issues and Pull Requests was added yesterday night on: 
- https://github.com/sailuh/kaiaulu/commit/5a003899207fd55980a9d9df1c5584e339854508 

The supporting notebooks for communication are these:

 - http://itm0.shidler.hawaii.edu/kaiaulu/articles/download_jira_data.html
 - http://itm0.shidler.hawaii.edu/kaiaulu/articles/download_github_comments.html

You can see example code on how to merge networks from various sources here:

  - http://itm0.shidler.hawaii.edu/kaiaulu/articles/reply_communication_showcase.html

------

The main complication here lies on tying identities across these sources. For example, if you look the notebooks above to download GitHub and JIRA, you will notice JIRA table only reports the user name. Meanwhile GitHub API table, as it obtains data from the Pull Request, Issue and Comments API endpoint, only report the GitHub user id. Meanwhile, mailing lists may contain user name and e-mail. 

Looking further, I was considering using the commit endpoint (https://docs.github.com/en/rest/reference/repos#commits) so we could look-up using the GitHub usernames, both name and e-mail so the linkage is viable. Both function and parser are already implemented in Kaiaulu: https://github.com/sailuh/kaiaulu/blob/5a003899207fd55980a9d9df1c5584e339854508/R/github.R#L220. 

Of course, this means that users that only post comments on issues but never modified code will have no name or e-mail tied to them, but given our interest in code modification without communication, then this should be fine.

Thoughts?

**Comment by harismumtaz18** [comment]
Thanks for detailed response, I think what you are suggesting is a viable solution. In terms of committers, I stumbled upon Apache Phone Book (http://home.apache.org/phonebook.html?unix=committers) and Committee information (https://projects.apache.org/committees.html) that can get us the committers. For instance, this link (https://projects.apache.org/committee.html?ambari) provides the list of committers of Ambari project. In addition, some projects (unfortunately, not all) provide the list of committers on their project webpages, like Ambari committers here (https://ambari.apache.org/team-list.html). Still, as you said we might have consistency issues because in some places not all the information is available so we have to rely on multiple credentials (name, email, id, login) of the committers for matching.

**Comment by carlosparadis** [comment]
Hi,

As of commit https://github.com/sailuh/kaiaulu/commit/e17a54141d4d367cb61684b3d58a1afe2884d4a1, the GitHub issues replies, GitHub pull request replies, JIRA Issue replies, and the Maling Lists or any combination of them can now be integrated and parsed via identity match. I've updated the social smells notebook to use `Helix` to showcase how this can be done. 

Note if less than all of these sources are used, you have to minimally modify the earlier code blocks to not  parse tables that do not exist. Namely:

https://github.com/sailuh/kaiaulu/blob/e17a54141d4d367cb61684b3d58a1afe2884d4a1/vignettes/social_smell_showcase.Rmd#L75-L77

https://github.com/sailuh/kaiaulu/blob/e17a54141d4d367cb61684b3d58a1afe2884d4a1/vignettes/social_smell_showcase.Rmd#L109-L113

https://github.com/sailuh/kaiaulu/blob/e17a54141d4d367cb61684b3d58a1afe2884d4a1/vignettes/social_smell_showcase.Rmd#L119-L155

From this point onwards no changes are necessary since all the reply tables from various sources are combined via the `rbind` above (which is just a row-wise bind).

You can download JIRA data using:

http://itm0.shidler.hawaii.edu/kaiaulu/articles/download_jira_data.html

and GitHub replies data using:

http://itm0.shidler.hawaii.edu/kaiaulu/articles/download_github_comments.html

For a test run, try using the current [helix.conf](https://github.com/sailuh/kaiaulu/blob/master/conf/helix.yml). I will try to refactor the project configuration files soon so it is more intuitive but for now, this one will get the job done (note the other confs are not yet updated). 

Feel free to re-open the issue if something is not clear.
