### ISSUE TITLE
Identity Matching Smells Notebook - Warnings

### ISSUE THREAD

**Issue by tuejari** [sailuh/kaiaulu#134]
In https://github.com/sailuh/kaiaulu/issues/126#issuecomment-913052673, @carlosparadis states regarding the implementations of community smells that "the textual names are mapped to a temporary id within function scope at this step." 

In the social smells notebook, in the section on Identity Matching

https://github.com/sailuh/kaiaulu/blob/5a003899207fd55980a9d9df1c5584e339854508/vignettes/social_smell_showcase.Rmd#L159-L179

The following is stated:

> You may also manually correct the identity numbers, before executing the remaining code blocks, to improve the accuracy of the results.

So, since the social smells implementation uses the textual names, the textual names also need to be manually corrected. 

After trying to manually fix some mistakes in the identity matching, I got the following warnings from this part of the social smells notebook: 

https://github.com/sailuh/kaiaulu/blob/master/vignettes/social_smell_showcase.Rmd#L193-L356

```
Warning in if (clust != neigh_membership) { :
  the condition has length > 1 and only the first element will be used
Warning in matrix(unlist(extra.clust.links), ncol = 2, byrow = TRUE) :
  data length [637] is not a sub-multiple or multiple of the number of rows [319]
```

Note that the first warning is repeated a lot of times, and the second warning occurs occasionally in between. 

I am using the following command to change the name in `project_mbox`:

```{r}
project_mbox[<index>]$reply_from <- ‘<new-name>’
```
So for example:
```{r}
project_mbox[20:25]$reply_from <- ‘Firstname Lastname <f.lastname@example.com>’
```

(Note that I also manually change the `identity_id`, but that is not causing issues, likely because it is not used.)

I have tried to fix the identities right after 

https://github.com/sailuh/kaiaulu/blob/5a003899207fd55980a9d9df1c5584e339854508/vignettes/social_smell_showcase.Rmd#L159-L179

@carlosparadis mentioned the following potential problems:
> You may be editing the incorrect column in the table. Assuming you are doing this after the identity match is executed, I believe there should be two columns: id, and name added to it. The id is as I said, the numerical identity. the name column on the other hand collapses all the various name a person had and put them in a single string separated by "|". 

The warnings occur when I change the `reply_from` column in `project_mbox`. If I do not change the `reply_from` column, but instead change the `raw_name` column, I do not get warnings anymore. So it may simply be the first case, that I edited the incorrect column in the table. However, it could also be the case that the column `raw_name` is not used correctly.

Assuming that the warnings arise from the cluster algorithm, 

https://github.com/sailuh/kaiaulu/blob/5a003899207fd55980a9d9df1c5584e339854508/vignettes/social_smell_showcase.Rmd#L285-L298

I noticed the following. When `network_mbox_slice` is created, the column `reply_from` is used, not the column `raw_name`:

https://github.com/sailuh/kaiaulu/blob/5a003899207fd55980a9d9df1c5584e339854508/R/network.R#L272-L284

@carlosparadis also mentioned another potential problem:
> Another potential problem is that you may be creating duplicates by re-assigning (in fact I'd wage this as a strong candidate to be the issue). There should only be one row for each identity, your error suggesting a vector of size > 2 in later portions of the code may be due to duplicates. 

However, I am not sure that I understand this correctly. Each identity can occur multiple times in `project_mbox`, repeated for each mail they sent in the mailing list. I have checked and I do not introduce duplicate rows in the data table, if that is what you meant. I simply alter the values in specific cells.  

@carlosparadis mentioned the following:
> If the code runs just fine before you try to make manual changes, and this is a simple value replacement, then the value assignment is likely the culprit. Either due to the wrong column, or the wrong assignment. This variable is at the end of the day just a table. 

The code does run just fine before I make any manual changes, so I do expect the value assignment to be the culprit. Specifically, when I change the column `reply_from`.

**Comment by tuejari** [comment]
> If the code runs just fine before you try to make manual changes, and this is a simple value replacement, then the value assignment is likely the culprit. Either due to the wrong column, or the wrong assignment. This variable is at the end of the day just a table.

I have just tried to run Kaiaulu on https://github.com/apache/iceberg/ without manually adjusting the identity matching and ran into the same repeated error, so the value assignment might not be the culprit. 

```
Warning in if (clust != neigh_membership) { :
  the condition has length > 1 and only the first element will be used
Warning in matrix(unlist(extra.clust.links), ncol = 2, byrow = TRUE) :
  data length [237] is not a sub-multiple or multiple of the number of rows [119]
```

**Comment by carlosparadis** [comment]
@tuejari just posting here what I sent you via e-mail for completeness. You can safely skip this post.

Thanks for sending me the iceberg data. The good news is: The warnings you are getting are benign, and you don't need to re-run the analysis for them, although it would be a good idea to pick 1 or 2 projects that you run with this fix just to make sure the warnings on the other projects (especially the ones you edited the identity table by hand) are not something else:

https://github.com/sailuh/kaiaulu/blob/5a003899207fd55980a9d9df1c5584e339854508/R/smells.R#L222

On this line, simply add [1] to the end of it resolves the issue.

Here's what going on: In the master branch, I am using a (arguably better) communication detection algorithm than the one used on the smells branch. One of the "better" things, is that it can detect developers who belong to more than 1 community. Indeed, in the master notebook I added visualization for that. 

The line I told you to change checks the group assignment a developer neighbor (anyone immediately connected to it). When said neighbor happens to be the black node, you end up with a warning on the if statement. I originally rewrote the functions to mimic exactly the behavior of the originals, and since the old community detection algorithm couldn't detect multiple group assignments, the sea of warnings was introduced. 

In a way, this quickfix does not leverage the new feature of the community algorithm by only taking into account one of the assignments, but I will pin that as a feature for future work for radio silence.
