### ISSUE TITLE
Definitions of socio-technical metrics

### ISSUE THREAD

**Issue by harrismumtaz** [sailuh/kaiaulu#140]
@carlosparadis, could you please provide the definitions of the socio-technical metrics (e.g., code_only_devs, num_tz) that are computed alongside social smells? In addition, could you please clarify whether you consider global developers or core developers while computing the metrics? Thanks

**Comment by carlosparadis** [comment]
The definition of the metrics can be found in the table 5.1 of Simone's dissertation (print page 58, pdf page 70). 

Strictly speaking, in a given time window of x months, where x is specified by you in the notebook, code only devs counts the number of unique identities present exclusively in the git log (as opposed to say, the mailing list). 

https://github.com/sailuh/kaiaulu/blob/44cebf8409d1403158a6f7e11f76c16d7662b1c3/vignettes/social_smell_showcase.Rmd#L357-L361


Num Tz counts the number of unique timezones of the developers of the sources you specified. 

https://github.com/sailuh/kaiaulu/blob/44cebf8409d1403158a6f7e11f76c16d7662b1c3/vignettes/social_smell_showcase.Rmd#L374-L391

I am not sure about the global metric question. But you can see from the above that it is counting both the reply network and identity and code from the table and variable names in the notebook.

It is important to remember that whatever is counted is what you specify to be in the reply network. If you specified both jira and mailing list, then you will be considering both on top of the git log side. 

Does this answer your question?

**Comment by harrismumtaz** [comment]
Thanks, @carlosparadis for the explanation. From the code snippets, it looks like you are considering global developers for computing the metrics. On page 63 of Simone's dissertation, core community members are defined and if you look at Table 5.1., there are also similar metrics for core developers only (e.g., core.code.devs. mail.core.devs). That got me confused. It is clarified now. Thanks.

**Comment by carlosparadis** [comment]
> Core developers are community members who actively
participate into development activities, are associated with important managerial
roles, have higher decisional power and pursue the goal of supporting and soliciting
software contributions and community participations

Right, so just to clarify, you *can* obtain this too on the notebook, with a bit of editing in the notebook. 

In Kaiaulu, the parse_gitlog function gives you a few parameter options:

https://github.com/sailuh/kaiaulu/blob/44cebf8409d1403158a6f7e11f76c16d7662b1c3/R/network.R#L13

https://github.com/sailuh/kaiaulu/blob/44cebf8409d1403158a6f7e11f76c16d7662b1c3/R/network.R#L65

You will see both offer file level `author` or `committer`. You can also do that at function level or other aggregation for entity:

https://github.com/sailuh/kaiaulu/blob/44cebf8409d1403158a6f7e11f76c16d7662b1c3/R/network.R#L126

https://github.com/sailuh/kaiaulu/blob/44cebf8409d1403158a6f7e11f76c16d7662b1c3/R/network.R#L177

So this gives you concretely with 3 fill in the blank: Author/Commiter | File/Function/OtherEntity | Bipartite/Temporal. 

The social smell notebook makes the choice for you:

https://github.com/sailuh/kaiaulu/blob/44cebf8409d1403158a6f7e11f76c16d7662b1c3/vignettes/social_smell_showcase.Rmd#L321-L322

But you can change the parameters so you can have core developers. Kaiaulu most relies on the definition used by git itself, of authors and committers so there is no conceptual ambiguity tied to a paper (since definitions on papers change very often). Authors are people who make the changes. Commiters are those who commit them. They can both be the same person or different. 

There are some notebooks in Kaiaulu that discuss the implications of the 3 parameters too. See them on pretty print on: http://itm0.shidler.hawaii.edu/kaiaulu/articles/gitlog_showcase.html for example on the bipartite vs temporal with example network visualizations :) . 

Lastly, you can edit yourself the parsed project git log. E.g. you can subset the `project_gitlog` based on a list of names yourself based on, say, the project website claims to be the "core developers"!

**Comment by harrismumtaz** [comment]
Like this flexibility, thanks :)
