### ISSUE TITLE
Improving Kaiaulu Documentation

### ISSUE THREAD

**Issue by leilani-reich** [sailuh/kaiaulu#151]
We will add improvements to the Kaiaulu documentation. These will include clarity on the Social Smells notebook and other vignettes, grammar/spelling fixes, and improvements on the function docs.

Tasks:

Leilani:https://github.com/sailuh/kaiaulu/pull/158
Pull Request: 
- [x] Documentation fixes

Nico:
Pull Request: https://github.com/sailuh/kaiaulu/pull/161
- [x] Documentation fixes

Malia:
Pull Request: https://github.com/sailuh/kaiaulu/pull/157
- [x] Documentation fixes

**Comment by carlosparadis** [comment]
Thank you! 

I would like to refine a bit what is being sought here. Several artifacts together compose the documentation of Kaiaulu: 

   1. (*) **README.md**
2. CONTRIBUTING.md (as pointed out in #150)
3. (*) config files (be them either the /conf and tools.yml). (I.e. consider the commentary around each field that may be lacking, for example #146, or the overall template itself) 
4. the wiki (as improved in #145)
5. the Kaiaulu major use cases (references.bib) 
6. (*) **The notebooks** (not all of them have a narrative explaining the process or the config file)
7. (*) **the documentation on each function in R/** (e.g. when you type `?parse_gitlog`. 
8. **pkgdown docs**: i.e. http://itm0.shidler.hawaii.edu/kaiaulu (this is auto generated by an R package named pkgdown, but it is still an easier way to navigate the function docs, vignettes and NEWS.md). 
9. the tags on GitHub used to annotate the issues, and the template of issues themselves (which is currently none)
10. Of course, the published paper itself gives the conceptual intent behind the tool and the vision, but that can't be edited. 
11. The man pagage of Kaiaulu CLI, which is the server-side endpoint of Kaiaulu (https://github.com/sailuh/kaiaulu/tree/master/exec) 

The (*) emphasizes the ones I believe are more critical, but if your usage of them suggests otherwise, then that is ok and helpful to know too!

For this deliverable, I would like you to take a comprehensive view of all the artifacts made available, which together form your user experience when first installing the package. Here's a suggestion of section template for this deliverable:

  1. Enumerate the documentation artifacts (as above, and/or any other I may have missed).
  2. The task you are trying to perform. This would be the one provided to you by @rnkazman with Apache Thirft. More specifically, using the package for computing Social Smells, composing the config file for Apache Thirft, and collaborating in GitHub (pull request). 
  3. Enumeration of difficulties in accomplishing the task. 
  4. For each difficulty enumerated, map them to the appropriate one or more artifact(s) and note what exactly caused confusion or was lacking.
  5. List of proposed changes.
  6. Subsequent commit hashes associated with addressing them for this issue. 

This will give us comprehensive coverage of existing issues, and, perhaps even as importantly, very helpful examples for future contributions to use and learn by example. Note it is ok you do not address every single identified documentation issue here since there are other deliverables. If that is the case, please still mention them, since that is helpful for future contributions.

-------------------

A second ask I have is a Cheatsheet for the task you performed, i.e. social smell analysis and/or any other functions you think are helpful a new user should know. An example can be found in data.table: https://github.com/Rdatatable/data.table. The templates and other examples can be found here: https://github.com/rstudio/cheatsheets/tree/main/powerpoints

You can also refer to data.table overall documentation structure for ideas. 

-------------

Lastly, and this is more a FYI,  I believe you asked for code style guidelines, etc. In general, I try to use https://devguide.ropensci.org/ as a reference point, since, in the future Kaiaulu may be submitted there. You will find, for example, the practice of using a NEWS.md template is also noted there :) 

https://devguide.ropensci.org/newstemplate.html 

However, in the interest of time, I recommend you go by example based on what you see in the codebase and CONTRIBUTING.md. 

As with everything, @rnkazman has the final say in regard to scope and deliverables. The above is more a suggestion on what I believe would benefit the tool the most from a development and usage standpoint and/or look meaningful for your midterm reports. So please iterate with him on the weekly meetings and update this issue with the final deliverable proposal.

**Comment by nicoelee123** [comment]
Hello, I was reading through the documentation on http://itm0.shidler.hawaii.edu/kaiaulu/index.html. I was responsible for grammar mistakes and I found a couple that are listed below. I'm still reading everything in its entirety so I'll add as I continue to find more. For each improvement I'll post a link to the page, and a brief description of its location along with a quote of the error so you can use Ctrl+F.

(1) http://itm0.shidler.hawaii.edu/kaiaulu/index.html
"Features"
- "Parser to Network Transformations"
- - "...making easier to extend analysis in..."

Suggestion: "...making [it] easier to extend analysis in..."

(2) http://itm0.shidler.hawaii.edu/kaiaulu/articles/blamed_line_types_showcase.html
"Project Configuration File"
- "Kaiaulu defers to the project configuration file the choice of line types"

Suggestion: "Kaiaulu chooses the line types from the project configuration file."

(3) http://itm0.shidler.hawaii.edu/kaiaulu/articles/blamed_line_types_showcase.html
"Kaiaulu's GitHub wiki page also provides more details on Universal Ctags various flags."

Suggestion: "Refer to Kaiaulu's Github wiki page for more details on Universal Ctag's various flags."

(4) http://itm0.shidler.hawaii.edu/kaiaulu/articles/bug_count.html
A paragraph above the header "Parse Git Log"
- "We can capitalize on this assumption to detect which issue commits in the git log are trying to fix."

Suggestion: This sentence seemed generally vague and I had to read it a couple times to understand what it meant. Could possibly say "We can use this assumption to find the issues that the git log commits are trying to fix."

(5) http://itm0.shidler.hawaii.edu/kaiaulu/articles/bug_count.html
"With the added information per commit per file of which commits were associated to issues which were bugs, we can then group by filepath, the number of issues which the type is bug. The following show the top 20 buggiest files:"

Suggestion: This entire sentence was confusing to read personally. If I understood it correctly, a possible improvement could be wording it like this: "For each file, we now know the commits that were associated with fixing bugs. We then group the number of bug-related issues by file path. Our result should show the number of bugs per file path. The following outputs the top 20 files with the most bugs: "

(6) http://itm0.shidler.hawaii.edu/kaiaulu/articles/community_detection_showcase.html
"Introduction"
- "The later leverages said..."

Suggestion: "The latter leverages said..."

This page seems to need more explanation in general. There were a lot of coding examples and outputs but no explanation other than the Introduction.

**Comment by leilani-reich** [comment]
Hi Carlos, here are some of the suggestions we propose for Kaiaulu. We will edit as needed.

## Social Smells
1. In Social Smells, running parse_mbox did not work at first. It could be clarified that we need to download Perceval and its dependencies for this to run. In addition, it should be noted that Perceval 0.12.24 is one of the only versions that works with the parse_mbox function. Newer versions of Perceval do not work. Although it is mentioned in the README, it should be clearer in the Social Smells notebook
2. Near the end of Social Smells, there is a section here https://github.com/sailuh/kaiaulu/blob/c968a6ded22610db52e9aaa261d258d5d7128976/vignettes/social_smell_showcase.Rmd#L301-L307 where we need to specify the start and end commits in our thrift.yml config file such that they overlap dates in both the project_reply and project_git tables. It is not obvious that these two tables may not cover the same date range, so this should be clarified.
3. Provide example of getting necessary file path in different operating system.
Parse_gitlog function will contains path.expand (parser.R line 17)
5. Some packages might not be downloadable by install.packages(“packages_name”), recommend possible solutions
Ex: devtools::install_github("matbmeijer/JirAgileR")
On Ubuntu the libfontconfig1-dev package and libharfbuzz-dev package are required. 
libfontconfig1-dev package: sudo apt -y install libfontconfig1-dev"
libharfbuzz-dev package: sudo apt-get install libharfbuzz-dev libfribidi-dev
## README.md
6. It should be more apparent in general that we need to install certain packages like OSLOM (in tools.yml) for the Social Smells notebook to work. I think we could fix this by linking the Kaiaulu dependencies on the README and clarifying to the user what they should have. We should also mention here that Perceval 0.12.24 is tested to work with Kaiaulu, but not newer versions.
7. To set up the environment for completing Social Smells, the README could have more instruction on how to create python virtual environments and describing what different commands do, such as “which perceval”, which we could add.
8. For Windows users to try and run the vignettes, they may run into more issues. In the README, it says Kaiaulu has been tested on OS X and Ubuntu. It may be helpful to warn other OS users of potential issues and to guide them on how to use Kaiaulu via an Ubuntu virtual machine for instance.
9. For a first time user of Kaiaulu and perhaps someone unfamiliar with Github, it would be good to know about the wiki page by mentioning it in the README.
## download_jira_data.md & download_github_comments.md
10. The project config file section in the download_jira_data and download_github_comments could have more explanation to clarify what the code is doing and make it clear to the user. In particular, it would be good to clarify what exactly the save_path_issue_tracker_issues and save_path_issue_tracker_issue_comments mean.
## Project config files
11. The config files could have more explanation to help guide the user in regards to completing the vignettes efficiently. We could provide more information from the vignettes in the project config files so that users could better understand what each of the fields is saying.
12. There should be more explanation on what a github token is, a link on how to acquire it, and the fact that we need to put it in a text file here https://github.com/sailuh/kaiaulu/blob/c968a6ded22610db52e9aaa261d258d5d7128976/vignettes/download_github_comments.Rmd#L50
13. When running the gitlog section of the Social Smells notebook, it would be helpful if the config files contained an explanation on where the .git file is, since it's a hidden file. Maybe mention the command "ls -a" so users can see it is in the project repo directory.
## Wiki
14. Would be good to clarify (i.e. provide a link) to explain what a mirror is on the wiki here https://github.com/sailuh/kaiaulu/wiki/Analyzing-Projects.
15. Is the Depends section supposed to be empty? https://github.com/sailuh/kaiaulu/wiki/Depends. If not, details should be added.
## Function Documentation
16. The function descriptions in https://rdrr.io/github/sailuh/kaiaulu/api/ are very short and should be more descriptive to tell the user what they do. We could fix this by using how they are described in the vignettes to add more details to the functions, particularly ones used for Social Smells.
## Extra
17. Creating an issue template for bug reports, proposed changes to Kaiaulu, etc would be a helpful thing to add to improve the repo.

**Comment by leilani-reich** [comment]
[social-smells-cheatsheet.pdf](https://github.com/sailuh/kaiaulu/files/10833219/social-smells-cheatsheet.pdf)

Hi Carlos, I've made a cheatsheet for social smells. I wasn't sure what folder to put it in, so I've uploaded it here.
