### ISSUE TITLE
DV8 Integration Functions - Leilani

### ISSUE THREAD

**Issue by leilani-reich** [sailuh/kaiaulu#168]
This is a followup to issue #165, specific to my tasks for DV8 Integration.

TASKS:

Pull Request: https://github.com/sailuh/kaiaulu/pull/171

Milestone 3.3:
- [x] dv8_clsxb_to_clsxj() (core:export-cluster)
- [x] parse_dependencies() changes ~dv8_depends_to_sdsmj()~ (call Depends command for sdsm.json)
- [x] parse_dv8_clusters()

Milestone 3.4:
- [x] dependencies_to_sdsmj()
- [ ] gitlog_to_hdsmj()

**Comment by leilani-reich** [comment]
Hi Carlos,
I have made wrapper functions for dv8_clsxb_to_clsxj() and dv8_depends_to_sdsmj().

## dv8_clsxb_to_clsxj() 

### core:export-cluster command Info

```
usage: dv8-console core:export-cluster [-h] [-outputFile <OUTPUTFILE>] [-xml] INPUT_FILE
Export clustering as a separate XML or JSON file
 -h,--help                  Print usage information for a command
 -outputFile <OUTPUTFILE>   The output file to create
 -xml                       Export in XML (instead of JSON) format
```

### Wrapper function

```r
#' Exports DV8 clustering (.dv8-clsx) as a separate JSON file
#'
#' @param dv8_path path to dv8 binary
#' @param clustering_path path to clsx to convert to json
#' @param output_path path to save output file
#' @export
dv8_clsxb_to_clsxj <- function(dv8_path, clustering_path, output_path){
  system2(dv8_path, args=c('core:export-cluster', '-outputFile', output_path, clustering_path), stdout=FALSE, stderr=FALSE)
}
```

Note: I did not include the "-xml" option since you had mentioned we only cared about json output.

### Example of calling wrapper function

```r
# Load in the DV8 file
tools_path <- "../tools.yml"
tool <- yaml::read_yaml(tools_path)
dv8_path <-tool[["dv8"]]

# Load in the config file
conf_path <- "../conf/helix.yml"
conf <- yaml::read_yaml(conf_path)

clustering_path <- conf[["analysis"]][["dv8"]][["clustering"]][["clsxb"]]
output_path <- conf[["analysis"]][["dv8"]][["clustering"]][["clsxj"]]
dv8_clsxb_to_clsxj(dv8_path, clustering_path, output_path)
```

## dv8_depends_to_sdsmj()


### Depends command Info

```
Usage: depends [-hms] [--auto-include] [-d=<dir>] [-g=<granularity>]
               [-p=<namePathPattern>] [-f=<format>[,<format>...]]...
               [-i=<includes>[,<includes>...]]... <lang> <src> <output>
      <lang>                 The language of project files: [cpp, java, ruby, python,
                               pom]
      <src>                  The directory to be analyzed
      <output>               The output file name
      --auto-include         auto include all paths under the source path (please
                               notice the potential side effect)
  -i, --includes=<includes>[,<includes>...]
                             The files of searching path
  -d, --dir=<dir>            The output directory
  -f, --format=<format>[,<format>...]
                             The output format: [json(default),xml,excel,dot,
                               plantuml]
  -g, --granularity=<granularity>
                             Granularity of dependency.[file(default),method,L#(the level of folder. e.g. L1=1st level folder)  ]
  -h, --help                 Display this help and exit
  -s, --strip-leading-path   Strip the leading path.
  
  -m, --map                  Output DV8 dependency map file.
  -p, --namepattern=<namePathPattern>
                             The name path separators.[default(/),dot(.)
```

### Wrapper function

```r
#' Get Depends sdsm.json from a project src
#'
#' @param depends_path path to depends binary
#' @param lang language of project files: [cpp, java, ruby, python, pom]
#' @param src_path path to directory to be analyzed
#' @param output_path path to save output file
#' @export
dv8_depends_to_sdsmj <- function(depends_path, lang, src_path, output_path){
  #  Command for reference: java -jar depends.jar java ../../github/ics496/helix depends-0.9.6-output-no-map
  system2('java', args=c('-jar', depends_path, lang, src_path, output_path), stdout=FALSE, stderr=FALSE)
}
```

### Example of calling wrapper function

```r
# Load in the DV8 file
depends_path <-tool[["depends"]]

# Load in the config file
conf_path <- "../conf/helix.yml"
conf <- yaml::read_yaml(conf_path)

lang <- conf[["analysis"]][["dv8"]][["depends"]][["lang"]]
src_path <- conf[["analysis"]][["dv8"]][["depends"]][["src"]]
output_path <- conf[["analysis"]][["dv8"]][["depends"]][["sdsm"]]
dv8_depends_to_sdsmj(depends_path, lang, src_path, output_path)
```

I had several questions on the wrappers.

1. Should I have all the Depends command options in my wrapper as parameters? I only used what was necessary for this function for now. I have also not included the -m flag because of its weird behavior.

2. Do I need the help "-h" flag at all as a parameter to my wrappers? I didn't include it since the docs we will add for DV8 should tell the user how the functions work.

3. In general, do you want stdout is set to FALSE for the system2 commands, or TRUE? It may help the user identify a problem in their code, but also, the output for the Depends wrapper was very long, so I have left it as FALSE for now.

4. Also, I'm thinking we will need a separate section for dv8 to the config files. Would it look something like this as a template for the user? So they would replace the word "project" with the specific project they are analyzing, such as "helix". This is what I used to get the paths in my examples above.

```r
analysis:
  window:
     ...
  dv8:
    clustering:
      clsxb: ../../rawdata/dv8/project-hier.dv8-clsx
      clsxj: ../../rawdata/dv8/project-hier.json
    depends:
      src: ../../rawdata/git_repo/project
      sdsm: ../../rawdata/dv8/project-sdsm.json
      lang: java
```

Please let me know what you think. Thanks.

**Comment by carlosparadis** [comment]
> 1. Should I have all the Depends command options in my wrapper as parameters? I only used what was necessary for this function for now. I have also not included the -m flag because of its weird behavior.

No, just defining in the function what is necessary to use the rest of DV8 pipeline is for the best. Please have a look at R/parse.R parse_dependencies() to see what flags I consider relevant for our purposes. If there is any you did not include on your function, please mention it here so we can agree if it is necessary for dv8. Also consider information I already defined on the config file for Depends: 

https://github.com/sailuh/kaiaulu/blob/72de4d8e3190cf3197261abc8bed14d049be71dd/conf/ambari.yml#L106-L124

I believe you have to account for this on the Depends Jar. It will not auto-detect the language, and you want to allow the user to specify what dependencies to compute (as this impact the analysis substantially). Consider among the parameters Depends offers if anything else may affect the data provided to DV8.

> 2. Do I need the help "-h" flag at all as a parameter to my wrappers? I didn't include it since the docs we will add for DV8 should tell the user how the functions work.

No, the function docs should be comprehensive enough. In R we expect users to ?function_name, rather than run a -h flag, so we should go with the standard (and also because that will reflect in itm0 docs, whereas the -h will not). 

> 3. In general, do you want stdout is set to FALSE for the system2 commands, or TRUE? It may help the user identify a problem in their code, but also, the output for the Depends wrapper was very long, so I have left it as FALSE for now.

Just leave as FALSE. User can always test the command directly on terminal if the worst comes to end. 

> 4. Also, I'm thinking we will need a separate section for dv8 to the config files. Would it look something like this as a template for the user? So they would replace the word "project" with the specific project they are analyzing, such as "helix". This is what I used to get the paths in my examples above.


```
analysis:
  window:
     ...
  dv8:
    clustering:
      clsxb: ../../rawdata/dv8/project-hier.dv8-clsx
      clsxj: ../../rawdata/dv8/project-hier.json
    depends:
      src: ../../rawdata/git_repo/project
      sdsm: ../../rawdata/dv8/project-sdsm.json
      lang: java
```

You will want to reuse the depends section already defined above in the config file, so it would not be included under dv8. 

Moreover, dv8 should also appear at the same level as depends, under `tool`:

https://github.com/sailuh/kaiaulu/blob/72de4d8e3190cf3197261abc8bed14d049be71dd/conf/ambari.yml#L104-L106 

And not under analysis. The analysis section is more related to experimental design parameters. For example, one common issue mid project reports, is that we can't annotate the time range used in the analysis to generate a file. A few weeks later, and after several e-mail exchanges, nobody knows anymore what time window of a project was used. So the project configuration file field for time range in analysis serve as a reminder and for re-execution of the code. 

In the case of dv8, in the dv8 notebook, one example where this would be used is to control the git log range we would use before calling `gitlog_to_hdsmj()`, or to perform a git checkout before `dependencies_to_sdsmj()`. Note neither function would take this value as parameters. It would be used in the notebook to prepare the data before they are called (There is an example of the git_checkout on the dv8 Notebook I sent you for example). 

As for the field in tools, I think in dv8 case we should adopt a single folderpath in the config file. For example:

```
tool:
  # Depends allow to parse file-file static dependencies.
   dv8:
      # the project folder path files in function calls will be used. 
      # The folder name will be used in the file names.
      folder_path: ../../rawdata/dv8_thrift
      # the architectural flaws thresholds that should be used
      architectural_flaws:
         clique_depends: call,use
         crossing_cochange: 2
         .
         .
         .
         change_cover: ?            
```

Note in the format above, you can assume and reuse the folder name in the files. It removes tedious work for the user to specify every file name, and ensures consistency in the DV8 notebook across the file names for a full run. It detracts some flexibility from choosing every file name, but I don't see why for a given analysis, the file names would be wanted different (and if really wanted, it could be passed manually to every function). 

Secondly, note I am including here the architectural_flaw section that Malia will need to provide you when working on dv8_hsdsmb_to_flaws(). The command in question requires a large number of parameters, i.e. arch-issue:arch-issue. These should be on the configuration file. 

As a rule of thumb, if a parameter affects the interpretation of results, it should be in the configuration file. This Kaiaulu assumes as a philosophy it is worth doing tedious work on, as it affects the interpretation of the results. So, if you see other command parameters of this kind in the pipeline, we should surface them to the config files. We want someone to look at a conf file, and be able to quickly tell what **assumptions** were made on the analysis, rather than shuffle through code for where they were hardcoded, to the extent this is possible.

**Comment by carlosparadis** [comment]
In retrospect, I forgot parse_dependencies() generated the DSM. In this case, you already have this function done for you. On your pull request, I want you to make one modification, however. Right now, `--dir=/tmp/'` is hardcoded. Make this a function parameter of parse_dependencies(), and set `/tmp/` as the default value of it (so it doesn't break existing code not specifying this parameter). 

You opted out to not use the `-m` flag, much as I do not in parse_dependencies(), correct? 

The function signature should then be:

function(depends_jar_path,git_repo_path,output_dir,language){

That way you can reuse parse_dependencies. No point in duplicating the function if they are fundamentally the same. Granted this function has the additional behavior of returning the parsed table to memory, but that's okay.

All functions should allow the user to choose the path. What ensures the consistency of the path on the dv8 folder config file is the R Notebook by consistently using it across all functions.  

Note you will also need to modify this line here: 

https://github.com/sailuh/kaiaulu/blob/72de4d8e3190cf3197261abc8bed14d049be71dd/R/parser.R#L564

And maybe a few others. Let me know if this breaks the file name consistency or anything else.

**Comment by carlosparadis** [comment]
I just remembered we never sorted out the -m flag on Depends, nor it seems you ever got a follow-up there. Considering you will write for 3.4 milestone a function to re-format data from Kaiaulu to DV8, this -m flag is likely required to be clear (so we know if you also need to generate this dv8 mapping file or copy and paste). 

In the interest of time, I sent an e-mail to DV8 group asking both about the -m flag being required for DV8 to ingest, and/or any specification they may have for the JSON format. Will update it here when I hear back.

**Comment by leilani-reich** [comment]
Sounds good, thank you!

**Comment by leilani-reich** [comment]
Hi Carlos,
I've created the parse_dv8_clusters() function. I utilized the example table you gave on the main DV8 issue (https://github.com/sailuh/kaiaulu/issues/165#issuecomment-1477482636) to help me understand what I needed to do and how to format the table.

## Output

The table is composed of three columns: layer, module, and file. I used the DV8 user guide https://archdia.com/pages/dv8-user-guide to learn more about this clustering hierarchy.

Each row shows the current layer, the current module, and the current file. From what I observed, layers can have multiple modules, and modules can have multiple files.

## My Process
I went through the DV8 diagram process to get the clustering file to pass to the core::export-cluster command (which I made the wrapper dv8_clsxb_to_clsxj() for) and acquire a json file. I analyzed the structure of the json and learned more about the layer, module, file composition. This helped me build the parse_dv8_clusters() function.

## How parse_dv8_clusters() works
The parse_dv8_clusters() itself takes in a single parameter, the path to the clustering.json output from the core::export-cluster command/dv8_clsxb_to_clsxj(). Then, it iterates through each of the layers, each of the modules, and finally to the file level to extract a row for the data table I create at the end. Each row contains the layer number, module number, and the current file the loop is looking at in the current module. Each row is added to a list. This list of lists gets converted into a datatable at the end.

## Preview of table output (called project_hier)
Here is what the data table looks like. I have called it project-hier since the input to the function (following the diagram you provided for DV8) is called project-hier.json:

layer | module | filename
-- | -- | --
L0 | M0 | /Users/xylent1/github/ics496/helix/zookeeper-api/src/main/java/org/apache/helix/zookeeper/constant/ZkSystemPropertyKeys.java
L0 | M1 | /Users/xylent1/github/ics496/helix/zookeeper-api/src/main/java/org/apache/helix/zookeeper/datamodel/serializer/PayloadSerializer.java
L0 | M2 | /Users/xylent1/github/ics496/helix/zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/exception/ZkBadVersionException.java
L0 | M2 | /Users/xylent1/github/ics496/helix/zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/exception/ZkException.java
L0 | M2 | /Users/xylent1/github/ics496/helix/zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/exception/ZkNoNodeException.java
L0 | M2 | /Users/xylent1/github/ics496/helix/zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/exception/ZkNodeExistsException.java
L0 | M3 | /Users/xylent1/github/ics496/helix/zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/IZkDataListener.java
L0 | M3 | /Users/xylent1/github/ics496/helix/zookeeper-api/

## parse_dv8_clusters() function
Here is what my parse_dv8_clusters() function looks like. I've explicitly shown the package names and have added comments to try and clarify each line of code. How does this look?

```r
#' Parse a clustering json from DV8
#'
#' @param clustering_path path to clustering json (obtained from dv8_clsxb_to_clsxj)
#' @export
#' @family parsers
parse_dv8_clusters <- function(clustering_path){
  # Read in the clustering file
  dv8_clusters_json <- jsonlite::read_json(clustering_path)
  
  # Get number of cluster layers in the json
  num_layers <- length(dv8_clusters_json$structure)
  
  # The structure field holds the relevant data
  structure <- dv8_clusters_json[["structure"]]
  
  # Will hold each row (a list of the current layer, module, and file) for the data table
  cluster_list <- list()
  
  # Iterate through each cluster
  for (i in 1: num_layers) {
    # Get the layer number (L0, L1, L2, ...)
    layer_i <- structure[[i]]$name
    
    # Get the number of modules for the current layer
    num_modules <- length(structure[[i]]$nested)
    
    # Iterate through each module
    for (j in 1: num_modules) {
      # Get the module number (M0, M1, M2, ...)
      LM_name <- stringr::str_split(structure[[i]]$nested[[j]]$name, "/")
      module_j <- LM_name[[1]][2]
      
      # Get number of files for the layer/module pair
      num_files_per_LM <- length(structure[[i]]$nested[[j]]$nested)
      
        # Iterate through each file
        for (k in 1: num_files_per_LM) {
          # Get the file name
          filename_k <- structure[[i]]$nested[[j]]$nested[[k]]$name
          
          # Represents a row in the table with the layer #, module #, and filename
          row_ijk <- list(layer_i, module_j, filename_k)
          
          # Append current row (made up of the layer number, module number, & filename) to a list
          cluster_list <- append(cluster_list, list(row_ijk))
        }
    }
  }
  
  # Create table from list of layer,module,file rows
  cluster_parsed <- data.table::rbindlist(cluster_list)
  
  # Rename result columns
  cluster_parsed <- dplyr::rename(cluster_parsed, "layer" = "V1", "module" = "V2", "filename" = "V3")
  
  # Return parsed cluster data table
  return(cluster_parsed)
}
```

```r
# Example of calling function
project_hier <- parse_dv8_clusters("../../../Downloads/project-hier.json")
project_hier
```


## Resources
I have attached a zip containing the json I used as input and the project_hier output table in an RDS file.

[dv8_parse_cluster.zip](https://github.com/sailuh/kaiaulu/files/11068466/dv8_parse_cluster.zip)

Thanks,
Leilani

**Comment by carlosparadis** [comment]
> Each row shows the current layer, the current module, and the current file. From what I observed, layers can have multiple modules, and modules can have multiple files.

Yes, you can see that visually on the .xlsx file you generated too. The modules are the black rectangles. And sometimes, depending on the project, you will find rectangles within rectangles. That's what the layers are for in the file, to indicate how deep they are within a given hierarchy. 

> Preview of table output (called project_hier)
 

Please re-order the columns so it is filename, module, and layer. Also, I believe parse_gitlog calls filename as filepath. You may want to check for consistency. 

In R, we generally want to avoid for loops since they are slow. Try re-doing it with lapply, sapply etc. Look-up R vectorization. Also, please open a PR and send a commit for code review requests, since it is hard to make comment in line on issues. 

Maybe have a look on some of the parser functions. I believe some have examples on how .json files are handled. But if you can extract the table, move forward to the next functions and revisit the code design later. Ideally you want to avoid the for loops on the next functions too.

**Comment by leilani-reich** [comment]
Hi Carlos, I looked at the dependencies.json generated from parse_dependencies(), as well as the table generated from this function, to try and understand how to create the dependencies_to_sdsmj() function to get the sdsm.json.

This is what the parsed dependencies table looks like:

src | dest | Call | Import | Use | Parameter | Contain | Create | Extend | Return | Implement | Cast | Throw | Annotation
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
/Users/xylent1/github/ics4helix-admin-webapp/src/main/java/org/apache/helix/webapp/HelixAdminWebApp.java | /Users/xylent1/github/ics4helix-admin-webapp/src/main/java/org/apache/helix/webapp/RestAdminApplication.java | 1 | 0 | 7 | 0 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 0
/Users/xylent1/github/ics4helix-admin-webapp/src/main/java/org/apache/helix/webapp/HelixAdminWebApp.java | /Users/xylent1/github/ics4zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java | 2 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
 /Users/xylent1/github/ics4helix-admin-webapp/src/main/java/org/apache/helix/webapp/HelixAdminWebApp.java | /Users/xylent1/github/ics4zookeeper-api/src/main/java/org/apache/helix/zookeeper/impl/client/ZkClient.java | 2 | 1 | 10 | 0 | 2 | 2 | 0 | 0 | 0 | 0 | 0 | 0
 /Users/xylent1/github/ics4helix-admin-webapp/src/main/java/org/apache/helix/webapp/HelixAdminWebApp.java | /Users/xylent1/github/ics4zookeeper-api/src/main/java/org/apache/helix/zookeeper/datamodel/serializer/ZNRecordSerializer.java | 1 | 1 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0
/Users/xylent1/github/ics4helix-admin-webapp/src/main/java/org/apache/helix/webapp/HelixAdminWebApp.java | /Users/xylent1/github/ics4zookeeper-api/src/main/java/org/apache/helix/zookeeper/datamodel/serializer/ByteArraySerializer.java | 1 | 1 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0





Looking at the depends.json, I noticed a few key fields:

variables - from what I observed, this field contains a list of all the unique filepaths used in both the src and dest columns.

cells - this field looks like the following:

**Comment by leilani-reich** [comment]
Hi Carlos, 
I looked at the dependencies.json generated from parse_dependencies(), as well as the table generated from this function, to try and understand how to create the dependencies_to_sdsmj() function to get the sdsm.json.

## This is what the parsed dependencies table looks like:

src | dest | Call | Import | Use | Parameter | Contain | Create | Extend | Return | Implement | Cast | Throw | Annotation
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
/Users/xylent1/github/ics4helix-admin-webapp/src/main/java/org/apache/helix/webapp/HelixAdminWebApp.java | /Users/xylent1/github/ics4helix-admin-webapp/src/main/java/org/apache/helix/webapp/RestAdminApplication.java | 1 | 0 | 7 | 0 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 0
/Users/xylent1/github/ics4helix-admin-webapp/src/main/java/org/apache/helix/webapp/HelixAdminWebApp.java | /Users/xylent1/github/ics4zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java | 2 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
 /Users/xylent1/github/ics4helix-admin-webapp/src/main/java/org/apache/helix/webapp/HelixAdminWebApp.java | /Users/xylent1/github/ics4zookeeper-api/src/main/java/org/apache/helix/zookeeper/impl/client/ZkClient.java | 2 | 1 | 10 | 0 | 2 | 2 | 0 | 0 | 0 | 0 | 0 | 0
 /Users/xylent1/github/ics4helix-admin-webapp/src/main/java/org/apache/helix/webapp/HelixAdminWebApp.java | /Users/xylent1/github/ics4zookeeper-api/src/main/java/org/apache/helix/zookeeper/datamodel/serializer/ZNRecordSerializer.java | 1 | 1 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0
/Users/xylent1/github/ics4helix-admin-webapp/src/main/java/org/apache/helix/webapp/HelixAdminWebApp.java | /Users/xylent1/github/ics4zookeeper-api/src/main/java/org/apache/helix/zookeeper/datamodel/serializer/ByteArraySerializer.java | 1 | 1 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0


## Looking at the depends.json, I noticed these fields:

schemaVersion - the version of the schema. It was 1.0 for my file.

name - the name of the project (ex. helix-sdsm).

variables - from what I observed, this field contains an array of all the unique filepaths used in both the src and dest columns. These filepaths look to be in lexicographic order.

cells - this field looks like the following:

```
"cells": [
    {
      "src": 0,
      "dest": 1,
      "values": {
        "Use": 7,
        "Call": 1,
        "Create": 1,
        "Contain": 1
      }
   },
    ...
]
```

The "src" value 0 refers to the index of the src filepath in the "variables" field array. Similarly, the "dest" value 1 refers to the index of the "dest" filepath in the "variables" field array. I double-checked the rows in the parse_dependencies table and saw that the values in those rows matched the values in the json. I matched rows using the indices given by the values for the "src" and "dest" fields to get the corresponding files at these indices in the "variables" fields array and matching this to the filepaths in the table rows.


## There are a couple of issues/concerns I have:

1. I took the filepaths in the src and dest columns of the parse_dependencies() outputted table, combined them, took the unique values only, and looked at the length of the list. I thought it would match up with the number of filepaths in the dependencies.json. However, it does not. In particular, I had 1390 unique values vs 1415 in the depends.json "variables" field array. I looked at the first few and last few values of the sorted filepaths list I made, and the depends json, but they matched, so I'm not sure what I'm missing in-between.

2. In addition, I noticed that the parse_dependencies() function is giving me weird filepaths. For instance, looking at the example table above, I will show the first src filepath in the parsed depends table versus what was in the sdsm json (which I got from calling core:export-matrix on a dv8-sdsm file).

Parsed depends table src filepath:
```
/Users/xylent1/github/ics4helix-admin-webapp/src/main/java/org/apache/helix/webapp/HelixAdminWebApp.java
```
sdsm.json src filepath:
```
"/Users/xylent1/github/ics496/helix/helix-admin-webapp/src/main/java/org/apache/helix/webapp/HelixAdminWebApp.java"
```

So it looks like the filepath gets cut off in the depends table, "ics4" when it should be "ics496/helix/". I think this may be a bug, unless I'm doing something wrong.

I've linked the sdsm.json I used and the depends table.
[parse_dependencies.zip](https://github.com/sailuh/kaiaulu/files/11071091/parse_dependencies.zip)

**Comment by carlosparadis** [comment]
Hi,

Please open another issue for the identified bug on parse_dependencies with the example provided above and link this issue (it is ok to copy and paste). 

I will not be able to look into this until at least the weekend, so I suggest you move forward with the function assuming the code is correct until either of us can identify the bug or defer this function to last and work on the other tasks in the meantime. 

I saw the PR too, and will keep an eye on it as you do commits. Let me know if any blockers surface.

**Comment by carlosparadis** [comment]
Hi, 

Here's an update from Yi in regards to your dependencies_to_sdmj() function:

> As far as I know we don't have that specification.

> The mapping file was no longer necessary in DV8 years ago if you look at the convert-matrix command, DV8 loads its built-in one if the file is not given explicitly. While you could still customize if needed, just refer to the example attached (exactly what Depends does output).

I am not attaching the file, since you already have it. Let me know if you need any further assistance for this function.

**Comment by carlosparadis** [comment]
Somewhere in this issue sea, I remember reading that the dependencies_to_sdsmj() and the gitlog_to_hdsmj() run super slow. I want to try and understand why. What exactly is the bottleneck? If they are super slow even for tiny projects, we won't be able to use them across various projects where we need them. Could you elaborate?

**Comment by carlosparadis** [comment]
@leilani-reich 

I am posting there since it will likely get lost in the discussion on the Pull Request changes. Let's leave this for revision 2 of this PR. For now, feel free to proceed as two separate functions if it is easier. 

You may remember I moved both the functions `dependencies_to_sdsmj` and `gitlog_to_hdsmj` to you for having a lot of overlap functionality. This revision request reflects why I asked so. Both the functions:

`dependencies_to_sdsmj()` and the function `gitlog_to_hdsmj()` are fundamentally using the code logic being discussed here: 

https://github.com/sailuh/kaiaulu/pull/171/files#r1167230670

They both take as input a graph (node + edgelist tables), and write that in a json format compatible to DV8. 

(p.s.: Note the graph format for parse_dependencies() will be added in a follow-up commit in order to address the issue mentioned in https://github.com/sailuh/kaiaulu/issues/189#issuecomment-1509292321). 

Therefore, your two functions should instead be a set of 3 functions. The code you wrote for parse_hdsmj() after suggested changes https://github.com/sailuh/kaiaulu/pull/171/files#r1167230670 should instead be generalized into a function:

`graph_to_dsmj()` and reside in R/graph.R. Said function would expect a variable `graph`, which is a list of two elements, nodes and edgelist (as you have observed in your `parse_hdsmj`). This function assumes the node table to be of the form:

| name | ... |
|--------|--------|
| value | ... | 

Where the "..." is any other number of columns the graph may have. For your function, these columns are ignored, since neither Depends nor DV8 does not annotate any information to the nodes other than their names (aka "variables" field). 

Meanwhile, the edgelist is of the form:

| from | to | \<weight1> | \<weight2> | ... | \<weighn>|
|--------|--------|--------|--------| --------|--------|
| Value | Value | Value |Value |... |Value |

Where weights1 through n is an arbitrary number of columns, where each represents a different weight to the edges. In Depends and DV8, these weights are the various dependency types a user may choose to include on Depends. 

Observe the following examples from both Gitlog and Dependencies in json for cells / edgelist:

```json
  "cells" : [ {
    "src" : 0,
    "dest" : 3,
    "values" : {
      "Cochange" : 1.0
    }
  }, {
    "src" : 1,
    "dest" : 2,
    "values" : {
      "Cochange" : 1.0
    }
```

```json
}, {
    "src" : 0,
    "dest" : 23,
    "values" : {
      "Use" : 3.0,
      "Import" : 1.0
    }
  }, {
    "src" : 0,
    "dest" : 1337,
    "values" : {
      "Import" : 1.0,
      "Call" : 1.0,
      "Create" : 1.0
    }
  }
```

As you can see, the format is the same, what changes is the columns the edgelist table has, which subsequently affects the fields that should be included under the cells "values" for every entry. If either the column doesn't exist on edgelist, or if that particular row of edgelist has value 0 for it, then it is not included.

This logic can be consistently captured in this generic `graph_to_dsmj()` function, and then reused for your functions `dependencies_to_sdsmj()` and `gitlog_to_hdsmj()`. 

Both these functions task is now only to rename the nodes and edgelist accordingly to names, from, to, etc, and then defer to `graph_to_dsmj()` the transformation. As such, these functions should reside in `R/network.R` alongside the transform functions, as you see that similar logic it is already implemented there:

https://github.com/sailuh/kaiaulu/blob/6d407d629a2646b3bd00d45e483447b1db7b7c01/R/network.R#L26-L41

At which point, it would make sense to rename them accordingly for consistency to:

`transform_dependencies_to_sdsmj()` and `transform_gitlog_to_hdsmj()`

Let me know if this makes sense. The code logic is fundamentally the same, other than we don't assume the column names on the Dependencies or Gitlog tables, but instead assume any remaining tables listed should be translated as Cell values in the json format.
