### ISSUE TITLE
DV8 Integration Functions - Malia

### ISSUE THREAD

**Issue by malialiu** [sailuh/kaiaulu#170]
Follow up to Issue https://github.com/sailuh/kaiaulu/issues/165

Pull Request: https://github.com/sailuh/kaiaulu/pull/174

Milestone 3.3:
- [x] dv8_hsdsmb_to_flaws() (arch-issue:arch-issue)
- [x] dv8_dsmj_to_dsmb() (core:convert-matrix)
- [x] parse_dv8_architectural_flaws()

Milestone 3.4:
- [x] dv8_hdsmb_sdsmb_to_hsdsmb (core:merge-matrix)

Milestone 3.5:
 - [x] dv8_clsxj_to_clsxb (core:convert-cluster)

**Comment by carlosparadis** [comment]
Hi Malia,

Thanks. You forgot to include the checkboxes (see Leilani's issue on DV8). 

Can you update the function names to match the more recent message first message on GitHub in #165? I see they are still showing command names.

Also, yours and @leilani-reich  `dv8_gitlog_to_sdsm()` are fundamentally the same. Can you decide on which of you will implement it?

**Comment by malialiu** [comment]
> Can you update the function names to match the more recent message first message on GitHub in #165? I see they are still showing command names.
> 
Okay, sorry about that.
> Also, yours and @leilani-reich `dv8_gitlog_to_sdsm()` are fundamentally the same. Can you decide on which of you will implement it?
>
Yes, Leilani will do that function.

**Comment by carlosparadis** [comment]
Sounds good! Please let me know if you have questions on this on this issue: 

https://github.com/sailuh/kaiaulu/issues/165#issuecomment-1477482636 

I know it is quite a bit to digest. Will try to get back to you on the bug parser soon.

Thanks!

**Comment by malialiu** [comment]
Hi Carlos, 

Based on the diagram https://github.com/sailuh/kaiaulu/issues/165#:~:text=by%20e%2Dmail-,%3A,-The%20function%20dv8_gitlog_to_hdsm, I think dv8_dsmj_to_dsmb() will use the sdsm.json file from dv8_depends_to_sdsmj(), then convert the sdsm.json file to dv8-dsm file. Am I in the right track? 
``` {r}
#' Convert from json to dv8-dsm file
#'
#' @param dv8_path path to dv8-console
#' @param sdsm_json_path path to sdsm.json
#' @param dv8_dsm_save_path path to save dv8-dsm file
#' @export
dv8_dsmj_to_dsmb <- function(dv8_path, sdsm_json_path, dv8_dsm_save_path){
  # Expand paths (e.g. "~/Desktop" => "/Users/someuser/Desktop")
  sdsm_json_path <- path.expand(sdsm_json_path)
  dv8_dsm_save_path <- path.expand(dv8_dsm_save_path)

  # Run system2 command
  system2(dv8_path, args=c('core:convert-matrix', '-outputFile', dv8_dsm_save_path, sdsm_json_path), stdout=FALSE, stderr=FALSE)
}

```

**Comment by carlosparadis** [comment]
Hi, 

Keep the functions simple, as you did with `dv8_dsmj_to_dsmb`. It is just a simple call. No need to assume the users will pass multiple files and embed that into the function. The loop can be done on an R Notebook by the user if needs be. All the system call functions are trivial like that. The one you will have to spend more time thinking is the parse_dv8_architectural_flaws(). 

I think the second function name is incorrect. Double check the diagram. 

Make sure you carefully document the function header of these functions. The user will not have the diagram as companion material when they look-up the function. E.g.

>  Convert from json to dv8-dsm file 

Convert what json? Be precise on the file names noted on that diagram in the docs. You may also want to check DV8 manual for the command, and/or the dv8-console --help of the command itself to make sure you included all the details.

**Comment by malialiu** [comment]
> Sounds good! Please let me know if you have questions on this on this comment on this issue instead:
> 
> [#165 (comment)](https://github.com/sailuh/kaiaulu/issues/165#issuecomment-1477482636)
> 
> I know it is quite a bit to digest.
> 
> I will also try to get back to you on the bug parser soon.
> 
> Thanks!

Hi Carlos,

Just want to make sure I understand this correctly. 

dv8_hsdsmb_to_flaws():
> 1. Open file-measure-report.csv, read the columns name to find the folder names
> 2. Open [column_name] folder
> 3. Open sub-folder in [column_name] folder
> 4. Convert .dv8-dsm file to json file
> 5. Get all the file paths in json file, and put in to the csv file with their [column-name] folder.
> 6. Repeat step 2 - 5 untill go through all [column-name] folders 
> 7. Return file-measure-report.csv file will all the file path

parse_dv8_architectural_flaws():
> 1. Read file-measure-report.csv
> 2. Returns a data table?

Let me know if I misunderstood this completely.

Thank you,
Malia

**Comment by malialiu** [comment]
Hi Carlos,

Is this look better? Let me know if I still need to change anything.

```{r}
#' Convert from sdsm.json to a dependency matrix in sdsm.dv8-dsm file
#'
#' @param sdsm_json_path path to sdsm.json
#' @param dv8_dsm_save_path path to save dv8-dsm file
#' @export
dv8_dsmj_to_dsmb <- function(sdsm_json_path, dv8_dsm_save_path){
  # Expand paths (e.g. "~/Desktop" => "/Users/someuser/Desktop")
  sdsm_json_path <- path.expand(sdsm_json_path)
  dv8_dsm_save_path <- path.expand(dv8_dsm_save_path)

  # Run system2 command
  system2('dv8-console', args=c('core:convert-matrix', '-outputFile', dv8_dsm_save_path, sdsm_json_path), stdout=FALSE, stderr=FALSE)
}

#' Merge matrices from sdsm.dv8-dsm file to one new matrix in hsdsm.dv8-dsm
#'
#' @param dv8_dsm_path_1 path to the matrix from sdsm.dv8-dsm file
#' @param dv8_dsm_path_2 path to the matrix from sdsm.dv8-dsm file
#' @param merged_dv8_dsm_path path to save the merged matrices in hsdsm.dv8-dsm file
#' @export
dv8_sdsmb_to_hsdsmb <- function(dv8_dsm_path_1, dv8_dsm_path_2, merged_dv8_dsm_path){
  # Expand paths (e.g. "~/Desktop" => "/Users/someuser/Desktop")
  dv8_dsm_path_1 <- path.expand(dv8_dsm_path_1)
  dv8_dsm_path_2 <- path.expand(dv8_dsm_path_2)
  merged_dv8_dsm_path <- path.expand(merged_dv8_dsm_path)

  # Run system2 command
  system2('dv8-console', args=c('core:merge-matrix', '-outputFile', merged_dv8_dsm_path, dv8_dsm_path_1, dv8_dsm_path_2), stdout=FALSE, stderr=FALSE)
}
```

Thank you,
Malia

**Comment by carlosparadis** [comment]
Hi, a reminder: Please use r instead of {r} on your code blocks on GitHub! R Studio code block is {r}, but GitHub will not highlight your code (I have been editing your past comments so I could have syntax highlight!). 

## dv8_hsdsmb_to_flaws() 

In regards to `dv8_hsdsmb_to_flaws()`: 

This function should be very simple, like the two you just posted above. You did a system call to arch-issue:arch-issue, and provide the path to its needed input. You also need to take in an output path, which will be provided to the `-outputFolder` parameter of the DV8 command. 

By the time this function is done executing, an output folder should be generated that resembles this:

<img width="964" alt="Screen Shot 2023-03-20 at 4 56 32 PM" src="https://user-images.githubusercontent.com/17270563/228497105-a8fd5e78-c13e-4316-8b46-39ff5e1a9270.png">

This concludes this function. Onwards to the next.

## parse_dv8_architectural_flaws() 

This is the harder function. 

> 1. Open file-measure-report.csv, read the columns name to find the folder names

No, you will not rely on file-measure-report.csv at all. But you have to assume as function parameter, the path to the folder output by arch-issue:arch-issue is provided to you. Your goal  with `parse_dv8_architectural_flaws()` is now to construct a different file to replace `file-measure-report.csv`, using information contained in the folder. You have to then make some assumptions in regards to how this folder will always look like, as shown above. For example:

<img width="202" alt="Screen Shot 2023-03-21 at 1 10 33 AM" src="https://user-images.githubusercontent.com/17270563/228499409-f4fbc6e4-1a28-4fbb-9580-97c8ae417da2.png">

Write a sub-function X (a function inside the function you are writing) that checks if the folders in this screenshot exist (use R's function list.files to obtain a list of the folders as a vector in R, then you can test the folder names shown on the screenshot). If the folders do exist, then you call another sub-function Y. 

Sub-function Y now assumes inside each folder, if they exist, i.e. clique, modularity-violation, etc there may be folders, and if they do exist, they will be numbered 1 through N. Once more, use list.files to obtain the list of folders that exist. Sub-function Y job is now delegates to sub-function Z a new task, that of converting binary merge-dsm in each folder, to a json dsm (using the R wrapper function to do so). 

Etc. 

The rest of the conceptual steps are noted on the original comment in #165, specifically: https://github.com/sailuh/kaiaulu/issues/165#issuecomment-1477482636. 

Please iterate with @leilani-reich the above comment, if the process here is still not clear, since she may be more familiar at this point with DV8 architecture given our back and forth. If you both are still not clear, feel free to ask here again in regard to these 2 functions. 

## Other functions there are code

Send me a PR with these so I can review. 

Thanks!

**Comment by malialiu** [comment]
Hi Carlos,

For function parse_dv8_architectural_flaws, there would be three sub-functions: check_folders_exist, convert_dsm_binary_to_json,  and generate_file_paths.
1. check_folders_exist
    - check a folder has theses sub-folders ("clique", "modularity-violation", "package-cycle", "unhealth-inheritance") or not
    - if a folder has all these sub-folders return true, else return false
2. convert_dsm_binary_to_json
    - call function dv8_hsdsmb_to_hierclsxb to convert merged.dv8-dsm file to dv8-clsx file
    - call function dv8_clsxb_to_clsxj to convert dv8-clsx file to json file
    - return json file path
3.  generate_file_paths
    - go over all the sub-folders in these folders ("clique", "modularity-violation", "package-cycle", "unhealth-inheritance")
    - convert all the merge.dv8-dsm in these sub-folders to json file
    - create a data table list all the json_file_path and which folder they belong to (Ex. clique/1)


``` r
#' Parse Architecture Flaws
#'
#' @param file_measure_report_path path to file-measure-report.csv
#' @param flaws_path path to architecture folder
#' @export
parse_dv8_architectural_flaws <- function(file_measure_report_path, flaws_path) {
  folders_expected <- c("clique", "modularity-violation", "package-cycle", "unhealth-inheritance")
  check_folders_exist <- function(folders_to_check, flaws_path) {
    folders_exist <- list.files(flaws_path)

    folder_exists <- all(sapply(folders_to_check, function(folder) any(grepl(folder, folders_exist))))

    return(folder_exists)
  }

  convert_dsm_binary_to_json <- function(dsm_binary_file_path, json_path) {
    hierclsxb_path <- file.path(json_path, 'tmp_hierclsxb.clsx')
    hierclsxb_path <- dv8_hsdsmb_to_hierclsxb(dsm_binary_file_path, hierclsxb_path)
    hierjson_path <- file.path(json_path, 'hier.json')
    dv8_clsxb_to_clsxj('dv8_console', hierclsxb_path, hierjson_path)
    file.remove(hierclsxb_path)
    return (hierjson_path)
  }

  generate_file_paths <- function(folders_expected, flaws_path) {
    # Initialize an empty data.table to store the file paths
    dt_files <- data.table(file_path = character(), folder_name = character())

    # Loop over each expected folder
    for (folder_name in folders_expected) {
      # Get the full path to the current folder
      folder_path <- file.path(flaws_path, folder_name)

      # Check if the sub-folder exists
      if (dir.exists(folder_path)) {
        # Get a list of all sub-folders in the current folder
        subdirs <- list.dirs(folder_path)

        # Loop over each sub-folders in the current folder
        for (subdir_name in subdirs) {
          # Get the full path to the current sub-folder
          subdir_path <- file.path(folder_path, subdir_name)

          # Get a list of all files in the current sub-folder
          files <- list.files(subdir_path, full.names = TRUE)

          # Get a list of all *merge.dv8-dsm file
          files_merged <- grep('merge', files, value = TRUE)

          # If there are any files that contain the word 'merge', add their paths to the data.table
          if (length(files_merged) > 0) {
            dt_subdir <- data.table(file_path = character(), folder_name = character())
            # loop through each file path in files_merged
            for (file_path in files_merged) {
              # call convert_dsm_binary_to_json for each dv8-dsm file
              save_path <- dirname(file_path)
              result <- convert_dsm_binary_to_json(file_path, save_path)

              # add the file path and result to the data.table
              dt_subdir <- rbind(dt_subdir, data.table(file_path = file_path, folder_name = paste0(folder_name, gsub(folder_path, '', subdir_path)), result = result))
            }
            dt_files <- rbind(dt_files, dt_subdir)
          }
        }
      }
    }

    # Return the data.table of file paths
    return(dt_files)
  }

  hier_json_file_paths <- ''

  if (check_folders_exist(folders_expected, flaws_path)){
    hier_json_file_paths <- generate_file_paths(folders_expected, flaws_path)
  }

  return (hier_json_file_paths)
}

```

**Comment by carlosparadis** [comment]
As agreed on the last meeting, we moved the code for Pull Request so I could offer feedback. I am moving the issue to In Progress status, but unless you have any other more general questions, we can just keep the status updated to the PR itself on the board until the task is done.

Let me know here if I missed any questions or revisions request.
