### ISSUE TITLE
User Experience Report III

### ISSUE THREAD

**Issue by carlosparadis** [sailuh/kaiaulu#262]
As agreed on call, please use this space to post your user experience reports (one post per report). For user questions, please use Discussions -> Q&A. Also welcome to post questions about this issue associated with the tasks.

**Comment by ian-lastname** [comment]
- [ ] https://github.com/sailuh/kaiaulu/discussions/264 - A part of the problem here is that I didn't exactly understand what ../.. meant. Because of this, I was not aware of where to put correctly put the missing directory that the function needed to actually run.
- [ ]

**Comment by Ssunoo2** [comment]
#263 devtools::test() returned several failures and after receiving help through the discussions tab and installing third-party dependencies, I was able to fix most of them. 

Perhaps more descriptive error messages such as “this failed because you did not install tool x” would be helpful. Many of the failures were fixed after installing third party apps, though the response in the discussion tab was helpful.

**Comment by anthonyjlau** [comment]
- [ ] #266 I am unable to run community_detection_showcase.Rmd because of an incorrect path.
